version: "3.2"

services:
  sql-server:
    image: app-docker-sql-server:latest
    container_name: app-docker-sql-server
    build:
      context: ../sql
      dockerfile: ./Dockerfile
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Teste@123"
      ACCEPT_EULA: "Y"

  api-docker:
    image: app-docker-api:latest
    container_name: app-docker-api
    build:
      context: ../src
      dockerfile: ./App.Docker.Api/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5001
    depends_on:
      - sql-server